### ISSUE TITLE
Blank windows and WARNING: _prefill_polygon: poly has too many indices to draw, increase batch buffer size

### ISSUE THREAD

**Issue by derivator** [setzer22/godot-egui#12]
Doing

```rust
Self {
    egui_test: egui_demo_lib::ColorTest::default()
}

//...

Window::new("Color Test").scroll(true).show(ctx, |ui| {
    self.egui_test.ui(ui, &mut None);
});

Window::new("Settings").scroll(true).show(ctx, |ui| {
   ctx.settings_ui(ui);
});
```
shows a blank window. Clicking the (invisible) checkbox to turn off [vertex gradients](https://github.com/emilk/egui/blob/f2b6edd6db0d59187e66481ef62909eee6f59610/egui_demo_lib/src/apps/color_test.rs#L301) makes the content visible. 

Possibly a related issue: settings menu turns blank if the following settings are selected: Painting > debug > Coarse culling off, Paint text bounds on, then expand multiple menus.

**Comment by jacobsky** [comment]
@derivator Thanks for opening an issue. Do you have a sample project that I could take a look at? I'm not 100% sure of the context/how the code is being called from Godot. Also, which version of the library are you using?

**Comment by derivator** [comment]
@jacobsky Thanks for the reply. [Example project here](https://github.com/derivator/GodotEguiTest). Using the newest versions of everything.

**Comment by jacobsky** [comment]
@derivator  Thanks for the sample project. It looks like the issue is due to `WARNING: _prefill_polygon: poly has too many indices to draw, increase batch buffer size`

This occurs due to how the batches are drawn. In the case of the color test, the polygon appears to be to big for the default settings.

I was able to resolve this by going into the Project settings -> Rendering -> Batching settings menu and increasing "Batch Buffer Size" to 65535.

I think we should create a small FAQ for issues like this.

**Comment by derivator** [comment]
@jacobsky thanks! Can't believe I missed that error message... :roll_eyes:
